"""create shop table

Revision ID: 6a5d4fd00796
Revises: 
Create Date: 2026-03-18 23:57:02.511271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5d4fd00796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('is_verified', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'blocked', 'deactivated', name='shopstatus'), nullable=True),
    sa.Column('rating', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops')
    # ### end Alembic commands ###
